/** Deutsch — German. */
import type { UIStrings } from './types';

export const strings: UIStrings = {
  searchPlaceholder: 'Den Garten durchsuchen … (Esc zum Schließen)',
  searchHint: 'Titel, Abschnitte und Fließtext, in dieser Sprache.',
  searchEmpty: 'Keine passende Notiz.',
  searchUnavailable: 'Der Suchindex konnte nicht geladen werden.',
  searchUnit: 'Seiten',
  searchScopeAll: 'Alle',
  searchDialog: 'Website-Suche',
  searchInput: 'Das Handbuch durchsuchen',
  searchResults: 'Suchergebnisse',
  searchButton: 'Suchen (⌘K)',

  languages: 'Sprache',

  breadcrumb: 'Brotkrümelnavigation',
  contents: 'Inhalt',
  chapterNav: 'Kapitelnavigation',
  prev: '← zurück',
  next: 'weiter →',
  hub: 'Hub',
  overview: 'Übersicht',
  updated: 'aktualisiert',
  backlinks: 'Verknüpfte Erwähnungen',
  localGraph: 'Lokaler Graph',
  lightbox: 'Bildbetrachter',
  close: 'Schließen',
  copied: 'Code in die Zwischenablage kopiert',
  copyFailed: 'Kopieren fehlgeschlagen – die Zwischenablage ist nicht verfügbar',
  theme: 'Helles / dunkles Farbschema umschalten',
  menu: 'Menü',
  skip: 'Zum Inhalt springen',
  partLabel: (roman) => `Teil ${roman}`,
  readingTime: (min) => `${min} Min. Lesezeit`,
  footer: 'astro-inkstone-Demo · die Notizen sind das Handbuch, das Handbuch ist die Demo',

  landingTitle: 'Ein Garten aus Papier und Tusche',
  landingDesc: 'Die astro-inkstone-Demo – ein Taxonomie-Garten, dessen Notizen zugleich das Handbuch des Pakets sind.',

  speakLabel: 'Im Klartext →',
  diffLabel: 'Gegenüber Vorarbeiten →',

  kinds: {
    guide: { label: 'Leitfaden', desc: 'Schritt für Schritt an einer Aufgabe entlang: hier anfangen, dann verdrahten' },
    reference: { label: 'Referenz', desc: 'Das vollständige Bild eines Teilsystems, laufend aktuell gehalten' },
    pattern: { label: 'Muster', desc: 'Eine Entwurfshaltung, die einen Namen verdient – samt Begründung' },
  },
  domains: {
    design: { label: 'Design', desc: 'Tokens, Theming, der Papier-und-Tusche-Look' },
    pipeline: { label: 'Pipeline', desc: 'Die Markdown-Pipeline: Dialekt, Plugins, Inhaltswächter' },
    components: { label: 'Komponenten', desc: 'Der Komponentensatz und wie man ihn zusammensetzt' },
    tooling: { label: 'Werkzeuge', desc: 'Prüfungen, Render-Proben und das CI-Setup' },
    editing: { label: 'Bearbeitung', desc: 'Die Bearbeitungsmaschine: Blöcke, Historie, KI, Posteingang' },
  },
  statuses: {
    seedling: { label: 'Sämling', desc: 'Ein Platzhalter – gepflanzt, noch nicht gewachsen' },
    growing: { label: 'Wachsend', desc: 'Ein lebendes Dokument, noch im Entstehen' },
    evergreen: { label: 'Immergrün', desc: 'Ausgereift und gepflegt' },
  },

  browse: {
    kicker: 'Garten',
    kickerSub: 'das Handbuch, als Notizen gewachsen',
    title: 'Papier & Tusche',
    titleSub: 'ein wachsender Garten aus Arbeitsnotizen',
    lede: (notes, domains) =>
      `Das Handbuch von astro-inkstone, als Garten gewachsen – ${notes === 1 ? '1 Notiz' : `${notes} Notizen`} in ${domains === 1 ? '1 Bereich' : `${domains} Bereichen`}, zu durchstöbern nach Art, Bereich und Schlagwort. Jeder Render-Effekt auf diesen Seiten ist das Paket selbst bei der Arbeit.`,
    sep: ' ',
    stop: '.',
    source: 'Quellcode:',
    thisPackage: 'dieses Paket',
    theEngine: 'die CMS-Engine –',
    editsThesePages: 'bearbeitet genau diese Seiten',
    recent: 'Zuletzt aktualisiert',
    recentSub: 'die drei zuletzt geänderten',
    shelfCount: (n) => `${n} primär · alle →`,
    allNotes: 'Alle Notizen →',
    byKind: 'Nach Art',
    byDomain: 'Nach Bereich',
    byStatus: 'Nach Status',
    byTag: 'Nach Schlagwort',
    facetLede: (desc, n) => `${desc} – ${n === 1 ? '1 Notiz' : `${n} Notizen`}.`,
    domainLede: (desc, n) => `${desc} – ${n === 1 ? '1 Notiz' : `${n} Notizen`}, primär oder sekundär.`,
    tagLede: (n) => (n === 1 ? '1 Notiz.' : `${n} Notizen.`),
    tagDesc: (tag, n) => `Notizen mit dem Schlagwort ${tag} (${n})`,
    facetDesc: (desc, n) => `${desc} (${n === 1 ? '1 Notiz' : `${n} Notizen`})`,
    all: 'Alle Notizen',
    allKicker: 'alles',
    allEntries: (n) => (n === 1 ? '1 Eintrag' : `${n} Einträge`),
    allDesc: (n) => `Alle Notizen des Gartens (${n}), neueste zuerst, mit Sofortfiltern.`,
    allLede: 'Neueste zuerst. Die Filterknöpfe darunter filtern direkt auf der Seite; ohne JavaScript führen sie auf die jeweiligen Facettenseiten.',
    dimKind: 'Art',
    dimDomain: 'Bereich',
    dimStatus: 'Status',
    dimTag: 'Schlagwörter',
    facetsAria: 'Facettennavigation',
    facetAll: 'Alle →',
    clear: 'Filter zurücksetzen',
    noMatch: 'Keine Notiz erfüllt alle gewählten Filter.',
    allTags: 'Alle Schlagwörter',
    chapters: (n) => `${n} Kapitel`,
  },
};
