/** Français — French. */
import type { UIStrings } from './types';

export const strings: UIStrings = {
  searchPlaceholder: 'Rechercher dans le jardin… (Esc pour fermer)',
  searchHint: 'Titres, sections et corps du texte, dans cette langue.',
  searchEmpty: 'Aucune note ne correspond.',
  searchUnavailable: 'L’index de recherche n’a pas pu être chargé.',
  searchUnit: 'pages',
  searchScopeAll: 'Tout',
  searchDialog: 'Recherche sur le site',
  searchInput: 'Rechercher dans le manuel',
  searchResults: 'Résultats de recherche',
  searchButton: 'Rechercher (⌘K)',

  languages: 'Langue',

  breadcrumb: 'Fil d’Ariane',
  contents: 'Sommaire',
  chapterNav: 'Navigation des chapitres',
  prev: '← précédent',
  next: 'suivant →',
  hub: 'Hub',
  overview: 'Vue d’ensemble',
  updated: 'mis à jour',
  backlinks: 'Mentions liées',
  localGraph: 'Graphe local',
  lightbox: 'Visionneuse d’images',
  close: 'Fermer',
  copied: 'Code copié dans le presse-papiers',
  copyFailed: 'Échec de la copie — le presse-papiers n’est pas disponible',
  theme: 'Basculer entre les thèmes clair et sombre',
  github: 'Code source sur GitHub',
  menu: 'Menu',
  skip: 'Aller au contenu',
  partLabel: (roman) => `Partie ${roman}`,
  readingTime: (min) => `${min} min de lecture`,
  footer: 'Démo astro-inkstone · les notes sont le manuel, le manuel est la démo',

  landingTitle: 'Un jardin de papier et d’encre',
  landingDesc: "astro-inkstone — le wiki Astro dans lequel on écrit. Typographie papier-et-encre pour la documentation, les wikis et les jardins numériques, avec édition sur place par astro-inkbrush. Cette démo est le manuel du paquet, écrit avec le paquet lui-même.",

  speakLabel: 'En clair →',
  diffLabel: 'Par rapport à l’existant →',

  kinds: {
    guide: { label: 'Guide', desc: 'Des parcours guidés par la tâche : commencez ici, branchez le tout' },
    reference: { label: 'Référence', desc: 'Le tableau complet d’un sous-système, tenu à jour' },
    pattern: { label: 'Patron', desc: 'Un parti pris de conception qui mérite un nom, raisons à l’appui' },
  },
  domains: {
    design: { label: 'Design', desc: 'Tokens, thèmes, le rendu papier et encre' },
    pipeline: { label: 'Pipeline', desc: 'La chaîne de traitement Markdown : dialecte, plugins, garde-fou du contenu' },
    components: { label: 'Composants', desc: 'Le jeu de composants et la façon de les assembler' },
    tooling: { label: 'Outillage', desc: 'Vérifications, sondes de rendu et le volet CI' },
    editing: { label: 'Édition', desc: 'La machine d’édition : blocs, historique, IA, boîte de réception' },
  },
  statuses: {
    seedling: { label: 'Pousse', desc: 'Une ébauche — plantée, pas encore développée' },
    growing: { label: 'En croissance', desc: 'Un document vivant, encore en cours d’écriture' },
    evergreen: { label: 'Pérenne', desc: 'Mûre et entretenue' },
  },

  browse: {
    kicker: 'Jardin',
    kickerSub: 'le manuel, cultivé note après note',
    title: 'Papier & encre',
    titleSub: 'un jardin de notes de travail qui continue de pousser',
    lede: (notes, domains) =>
      `Le manuel d’astro-inkstone, cultivé comme un jardin — ${notes} ${notes > 1 ? 'notes réparties' : 'note répartie'} sur ${domains} ${domains > 1 ? 'domaines' : 'domaine'}, à parcourir par type, domaine et étiquette. Chaque effet de rendu sur ces pages, c’est le paquet à l’œuvre.`,
    sep: ' ',
    stop: '.',
    source: 'Source :',
    thisPackage: 'ce paquet',
    theEngine: 'le moteur CMS —',
    editsThesePages: 'édite ces pages mêmes',
    recent: 'Mises à jour récentes',
    recentSub: 'les trois dernières modifiées',
    shelfCount: (n) => `${n} en principal · tout →`,
    allNotes: 'Toutes les notes →',
    byKind: 'Par type',
    byDomain: 'Par domaine',
    byStatus: 'Par statut',
    byTag: 'Par étiquette',
    facetLede: (desc, n) => `${desc} — ${n > 1 ? `${n} notes` : `${n} note`}.`,
    domainLede: (desc, n) => `${desc} — ${n > 1 ? `${n} notes` : `${n} note`}, en domaine principal ou secondaire.`,
    tagLede: (n) => (n > 1 ? `${n} notes.` : `${n} note.`),
    tagDesc: (tag, n) => `Notes étiquetées ${tag} (${n})`,
    facetDesc: (desc, n) => `${desc} (${n > 1 ? `${n} notes` : `${n} note`})`,
    all: 'Toutes les notes',
    allKicker: 'tout le jardin',
    allEntries: (n) => (n > 1 ? `${n} entrées` : `${n} entrée`),
    allDesc: (n) => `Toutes les notes du jardin (${n}), des plus récentes aux plus anciennes, avec filtres instantanés.`,
    allLede: 'Les plus récentes d’abord. Les pastilles ci-dessous filtrent sur place ; sans JavaScript, elles mènent aux pages de facettes.',
    dimKind: 'Type',
    dimDomain: 'Domaine',
    dimStatus: 'Statut',
    dimTag: 'Étiquettes',
    facetsAria: 'Navigation par facettes',
    facetAll: 'Tout →',
    clear: 'Effacer les filtres',
    noMatch: 'Aucune note ne satisfait tous les filtres sélectionnés.',
    allTags: 'Toutes les étiquettes',
    chapters: (n) => (n > 1 ? `${n} chapitres` : `${n} chapitre`),
  },
};
