/** हिन्दी — Hindi. */
import type { UIStrings } from './types';

export const strings: UIStrings = {
  searchPlaceholder: 'बगीचे में खोजें… (बंद करने के लिए Esc)',
  searchHint: 'शीर्षक, अनुभाग और मुख्य पाठ — इसी भाषा में।',
  searchEmpty: 'कोई मिलता-जुलता नोट नहीं।',
  searchUnavailable: 'खोज इंडेक्स लोड नहीं हो सका।',
  searchUnit: 'पेज',
  searchScopeAll: 'सभी',
  searchDialog: 'साइट खोज',
  searchInput: 'मैनुअल में खोजें',
  searchResults: 'खोज परिणाम',
  searchButton: 'खोजें (⌘K)',

  languages: 'भाषा',

  breadcrumb: 'ब्रेडक्रम्ब',
  contents: 'विषय-सूची',
  chapterNav: 'अध्याय नेविगेशन',
  prev: '← पिछला',
  next: 'अगला →',
  hub: 'हब',
  overview: 'अवलोकन',
  updated: 'अपडेट',
  backlinks: 'बैकलिंक',
  localGraph: 'लोकल ग्राफ़',
  lightbox: 'इमेज व्यूअर',
  close: 'बंद करें',
  copied: 'कोड क्लिपबोर्ड पर कॉपी हो गया',
  copyFailed: 'कॉपी नहीं हो सका — क्लिपबोर्ड उपलब्ध नहीं है',
  theme: 'लाइट / डार्क थीम बदलें',
  github: 'GitHub पर स्रोत कोड',
  menu: 'मेनू',
  skip: 'मुख्य सामग्री पर जाएँ',
  partLabel: (roman) => `भाग ${roman}`,
  readingTime: (min) => `पढ़ने में ${min} मिनट`,
  footer: 'astro-inkstone डेमो · नोट ही मैनुअल हैं, मैनुअल ही डेमो है',

  landingTitle: 'कागज़ और स्याही का बगीचा',
  landingDesc: "astro-inkstone — वह Astro विकि जिसमें आप सीधे लिख सकते हैं। दस्तावेज़ीकरण, विकि और डिजिटल गार्डन के लिए कागज़-और-स्याही टाइपोग्राफ़ी, astro-inkbrush से उसी जगह संपादन। यह डेमो इस पैकेज का मैनुअल है, जो इसी पैकेज से लिखा गया है।",

  speakLabel: 'आसान भाषा में →',
  diffLabel: 'पहले के कामों की तुलना में →',

  kinds: {
    guide: { label: 'गाइड', desc: 'काम के हिसाब से कदम-दर-कदम राह: यहाँ से शुरू करें, जोड़ते चलें' },
    reference: { label: 'संदर्भ', desc: 'एक उप-तंत्र की पूरी तस्वीर, हमेशा ताज़ा' },
    pattern: { label: 'पैटर्न', desc: 'नाम देने लायक एक डिज़ाइन-दृष्टि, कारणों समेत' },
  },
  domains: {
    design: { label: 'डिज़ाइन', desc: 'टोकन, थीम, कागज़-और-स्याही वाला रूप' },
    pipeline: { label: 'पाइपलाइन', desc: 'Markdown पाइपलाइन: बोली, प्लगइन, सामग्री-रक्षक' },
    components: { label: 'कंपोनेंट', desc: 'कंपोनेंट का सेट और उन्हें जोड़ने के तरीक़े' },
    tooling: { label: 'टूलिंग', desc: 'जाँचें, रेंडर-परख और CI का ढाँचा' },
    editing: { label: 'संपादन', desc: 'संपादन मशीन: ब्लॉक, इतिहास, AI, इनबॉक्स' },
  },
  statuses: {
    seedling: { label: 'अंकुर', desc: 'अभी बस बोया गया है — उगना बाक़ी है' },
    growing: { label: 'बढ़ रहा', desc: 'जीता-जागता दस्तावेज़, अभी लिखा जा रहा है' },
    evergreen: { label: 'सदाबहार', desc: 'परिपक्व, और लगातार सँभाला हुआ' },
  },

  browse: {
    kicker: 'बगीचा',
    kickerSub: 'नोटों की शक्ल में उगता मैनुअल',
    title: 'कागज़ और स्याही',
    titleSub: 'काम के नोटों का बढ़ता हुआ बगीचा',
    lede: (notes, domains) =>
      `astro-inkstone का मैनुअल, बगीचे की तरह उगाया हुआ — ${domains} क्षेत्रों में ${notes} नोट, जिन्हें प्रकार, क्षेत्र और टैग से ब्राउज़ किया जा सकता है। इन पन्नों पर जो भी रेंडरिंग असर दिखता है, वह यही पैकेज है — काम पर लगा हुआ।`,
    sep: ' ',
    stop: '।',
    source: 'सोर्स कोड:',
    thisPackage: 'यह पैकेज',
    theEngine: 'CMS इंजन —',
    editsThesePages: 'इन्हीं पन्नों को संपादित करता है',
    recent: 'हाल में अपडेट हुए',
    recentSub: 'सबसे हाल में बदले तीन नोट',
    shelfCount: (n) => `${n} मुख्य · सभी →`,
    allNotes: 'सभी नोट →',
    byKind: 'प्रकार से',
    byDomain: 'क्षेत्र से',
    byStatus: 'स्थिति से',
    byTag: 'टैग से',
    facetLede: (desc, n) => `${desc} — ${n} नोट।`,
    domainLede: (desc, n) => `${desc} — ${n} नोट, मुख्य या गौण क्षेत्र के तौर पर।`,
    tagLede: (n) => `${n} नोट।`,
    tagDesc: (tag, n) => `${tag} टैग वाले नोट (${n})`,
    facetDesc: (desc, n) => `${desc} (${n} नोट)`,
    all: 'सभी नोट',
    allKicker: 'सब कुछ',
    allEntries: (n) => (n === 1 ? '1 प्रविष्टि' : `${n} प्रविष्टियाँ`),
    allDesc: (n) => `बगीचे के सभी नोट (${n}), सबसे नए पहले, झटपट फ़िल्टर के साथ।`,
    allLede: 'सबसे नए पहले। नीचे दिए फ़िल्टर यहीं छाँटते हैं; JavaScript न हो तो ये उसी श्रेणी के पन्ने पर ले जाते हैं।',
    dimKind: 'प्रकार',
    dimDomain: 'क्षेत्र',
    dimStatus: 'स्थिति',
    dimTag: 'टैग',
    facetsAria: 'ब्राउज़ इंडेक्स',
    facetAll: 'सभी →',
    clear: 'फ़िल्टर हटाएँ',
    noMatch: 'कोई नोट सभी चुने हुए फ़िल्टरों पर खरा नहीं उतरता।',
    allTags: 'सभी टैग',
    chapters: (n) => `${n} अध्याय`,
  },
};
