/** Bahasa Indonesia — Indonesian. */
import type { UIStrings } from './types';

export const strings: UIStrings = {
  searchPlaceholder: 'Telusuri taman… (Esc untuk menutup)',
  searchHint: 'Judul, bagian, dan isi teks — dalam bahasa ini.',
  searchEmpty: 'Tidak ada catatan yang cocok.',
  searchUnavailable: 'Indeks pencarian gagal dimuat.',
  searchUnit: 'halaman',
  searchScopeAll: 'Semua',
  searchDialog: 'Pencarian situs',
  searchInput: 'Cari di buku panduan',
  searchResults: 'Hasil pencarian',
  searchButton: 'Cari (⌘K)',

  languages: 'Bahasa',

  breadcrumb: 'Jejak navigasi',
  contents: 'Daftar isi',
  chapterNav: 'Navigasi bab',
  prev: '← sebelumnya',
  next: 'berikutnya →',
  hub: 'Ikhtisar',
  overview: 'Ikhtisar',
  updated: 'diperbarui',
  backlinks: 'Tautan balik',
  localGraph: 'Graf lokal',
  lightbox: 'Penampil gambar',
  close: 'Tutup',
  copied: 'Kode disalin ke papan klip',
  copyFailed: 'Gagal menyalin — papan klip tidak tersedia',
  theme: 'Ganti tema terang / gelap',
  menu: 'Menu',
  skip: 'Langsung ke konten',
  partLabel: (roman) => `Bagian ${roman}`,
  readingTime: (min) => `${min} menit baca`,
  footer: 'Demo astro-inkstone · catatannya adalah panduan, panduannya adalah demo',

  landingTitle: 'Taman kertas dan tinta',
  landingDesc: "astro-inkstone — wiki Astro yang bisa Anda tulisi langsung. Tipografi kertas-dan-tinta untuk dokumentasi, wiki, dan taman digital, dengan penyuntingan di tempat lewat astro-inkbrush. Demo ini adalah panduan paket, ditulis dengan paket itu sendiri.",

  speakLabel: 'Bahasa awamnya →',
  diffLabel: 'Dibanding yang sebelumnya →',

  kinds: {
    guide: { label: 'Panduan', desc: 'Tuntunan langkah demi langkah per tugas: mulai di sini, lalu rangkai' },
    reference: { label: 'Referensi', desc: 'Gambaran utuh satu subsistem, selalu dimutakhirkan' },
    pattern: { label: 'Pola', desc: 'Sikap desain yang layak diberi nama, beserta alasannya' },
  },
  domains: {
    design: { label: 'Desain', desc: 'Token, tema, tampilan kertas-dan-tinta' },
    pipeline: { label: 'Pipeline', desc: 'Pipeline Markdown: dialek, plugin, penjaga konten' },
    components: { label: 'Komponen', desc: 'Kumpulan komponen dan cara merangkainya' },
    tooling: { label: 'Perkakas', desc: 'Pemeriksaan, uji render, dan penataan CI' },
    editing: { label: 'Penyuntingan', desc: 'Mesin penyuntingan: blok, riwayat, AI, kotak masuk' },
  },
  statuses: {
    seedling: { label: 'Bibit', desc: 'Rintisan — sudah ditanam, belum tumbuh' },
    growing: { label: 'Bertumbuh', desc: 'Dokumen hidup, masih terus ditulis' },
    evergreen: { label: 'Hijau abadi', desc: 'Matang dan terus dirawat' },
  },

  browse: {
    kicker: 'Taman',
    kickerSub: 'buku panduan yang tumbuh sebagai catatan',
    title: 'Kertas & tinta',
    titleSub: 'taman catatan kerja yang terus tumbuh',
    lede: (notes, domains) =>
      `Buku panduan astro-inkstone yang tumbuh menjadi taman — ${notes} catatan dalam ${domains} bidang, bisa dijelajahi menurut jenis, bidang, dan tag. Setiap efek render di halaman-halaman ini adalah hasil kerja paketnya sendiri.`,
    sep: ' ',
    stop: '.',
    source: 'Kode sumber:',
    thisPackage: 'paket ini',
    theEngine: 'mesin CMS —',
    editsThesePages: 'menyunting langsung halaman-halaman ini',
    recent: 'Baru diperbarui',
    recentSub: 'tiga yang terakhir berubah',
    shelfCount: (n) => `${n} utama · semua →`,
    allNotes: 'Semua catatan →',
    byKind: 'Menurut jenis',
    byDomain: 'Menurut bidang',
    byStatus: 'Menurut status',
    byTag: 'Menurut tag',
    facetLede: (desc, n) => `${desc} — ${n} catatan.`,
    domainLede: (desc, n) => `${desc} — ${n} catatan, sebagai bidang utama maupun sekunder.`,
    tagLede: (n) => `${n} catatan.`,
    tagDesc: (tag, n) => `Catatan dengan tag ${tag} (${n})`,
    facetDesc: (desc, n) => `${desc} (${n} catatan)`,
    all: 'Semua catatan',
    allKicker: 'semuanya',
    allEntries: (n) => `${n} entri`,
    allDesc: (n) => `Semua catatan di taman ini (${n}), yang terbaru di depan, dengan filter instan.`,
    allLede: 'Yang terbaru di depan. Tombol filter di bawah menyaring di tempat; tanpa JavaScript, tombol-tombol itu mengarah ke halaman indeks masing-masing.',
    dimKind: 'Jenis',
    dimDomain: 'Bidang',
    dimStatus: 'Status',
    dimTag: 'Tag',
    facetsAria: 'Indeks penjelajahan',
    facetAll: 'Semua →',
    clear: 'Hapus filter',
    noMatch: 'Tidak ada catatan yang memenuhi semua filter terpilih.',
    allTags: 'Semua tag',
    chapters: (n) => `${n} bab`,
  },
};
