/** Italiano — Italian. */
import type { UIStrings } from './types';

export const strings: UIStrings = {
  searchPlaceholder: 'Cerca nel giardino… (Esc per chiudere)',
  searchHint: 'Titoli, sezioni e corpo del testo, in questa lingua.',
  searchEmpty: 'Nessuna nota corrisponde.',
  searchUnavailable: 'Impossibile caricare l’indice di ricerca.',
  searchUnit: 'pagine',
  searchScopeAll: 'Tutto',
  searchDialog: 'Ricerca nel sito',
  searchInput: 'Cerca nel manuale',
  searchResults: 'Risultati della ricerca',
  searchButton: 'Cerca (⌘K)',

  languages: 'Lingua',

  breadcrumb: 'Percorso di navigazione',
  contents: 'Indice',
  chapterNav: 'Navigazione tra i capitoli',
  prev: '← precedente',
  next: 'successivo →',
  hub: 'Hub',
  overview: 'Panoramica',
  updated: 'aggiornato',
  backlinks: 'Menzioni collegate',
  localGraph: 'Grafo locale',
  lightbox: 'Visualizzatore di immagini',
  close: 'Chiudi',
  copied: 'Codice copiato negli appunti',
  copyFailed: 'Copia non riuscita — gli appunti non sono disponibili',
  theme: 'Alterna tema chiaro e scuro',
  menu: 'Menu',
  skip: 'Salta al contenuto',
  partLabel: (roman) => `Parte ${roman}`,
  readingTime: (min) => `${min} min di lettura`,
  footer: 'Demo di astro-inkstone · le note sono il manuale, il manuale è la demo',

  landingTitle: 'Un giardino di carta e inchiostro',
  landingDesc: "astro-inkstone — il wiki Astro in cui si scrive. Tipografia carta-e-inchiostro per documentazione, wiki e giardini digitali, con modifica sul posto tramite astro-inkbrush. Questa demo è il manuale del pacchetto, scritto con il pacchetto stesso.",

  speakLabel: 'In parole semplici →',
  diffLabel: 'Rispetto a prima →',

  kinds: {
    guide: { label: 'Guida', desc: 'Percorsi guidati da un compito: si parte da qui e si collega tutto' },
    reference: { label: 'Riferimento', desc: 'Il quadro completo di un sottosistema, tenuto aggiornato' },
    pattern: { label: 'Pattern', desc: 'Una scelta di design che merita un nome, con le sue ragioni' },
  },
  domains: {
    design: { label: 'Design', desc: 'Token, temi, l’aspetto carta e inchiostro' },
    pipeline: { label: 'Pipeline', desc: 'La pipeline Markdown: dialetto, plugin, il guardiano dei contenuti' },
    components: { label: 'Componenti', desc: 'Il set di componenti e come combinarli' },
    tooling: { label: 'Strumenti', desc: 'Controlli, sonde di rendering e il capitolo CI' },
    editing: { label: 'Editing', desc: 'La macchina di editing: blocchi, cronologia, IA, inbox' },
  },
  statuses: {
    seedling: { label: 'Germoglio', desc: 'Un abbozzo — piantato, non ancora cresciuto' },
    growing: { label: 'In crescita', desc: 'Un documento vivo, ancora in scrittura' },
    evergreen: { label: 'Sempreverde', desc: 'Maturo e curato' },
  },

  browse: {
    kicker: 'Giardino',
    kickerSub: 'il manuale, coltivato nota dopo nota',
    title: 'Carta e inchiostro',
    titleSub: 'un giardino di note di lavoro che continua a crescere',
    lede: (notes, domains) =>
      `Il manuale di astro-inkstone, cresciuto come un giardino — ${notes === 1 ? '1 nota' : `${notes} note`} in ${domains === 1 ? '1 ambito' : `${domains} ambiti`}, da sfogliare per tipo, ambito e tag. Ogni effetto di rendering su queste pagine è il pacchetto all’opera.`,
    sep: ' ',
    stop: '.',
    source: 'Sorgente:',
    thisPackage: 'questo pacchetto',
    theEngine: 'il motore CMS —',
    editsThesePages: 'modifica proprio queste pagine',
    recent: 'Aggiornate di recente',
    recentSub: 'le ultime tre modificate',
    shelfCount: (n) => (n === 1 ? '1 principale · tutte →' : `${n} principali · tutte →`),
    allNotes: 'Tutte le note →',
    byKind: 'Per tipo',
    byDomain: 'Per ambito',
    byStatus: 'Per stato',
    byTag: 'Per tag',
    facetLede: (desc, n) => `${desc} — ${n === 1 ? '1 nota' : `${n} note`}.`,
    domainLede: (desc, n) => `${desc} — ${n === 1 ? '1 nota' : `${n} note`}, come ambito principale o secondario.`,
    tagLede: (n) => (n === 1 ? '1 nota.' : `${n} note.`),
    tagDesc: (tag, n) => `Note con tag ${tag} (${n})`,
    facetDesc: (desc, n) => `${desc} (${n === 1 ? '1 nota' : `${n} note`})`,
    all: 'Tutte le note',
    allKicker: 'tutto il giardino',
    allEntries: (n) => (n === 1 ? '1 voce' : `${n} voci`),
    allDesc: (n) => `Tutte le note del giardino (${n}), dalla più recente, con filtri istantanei.`,
    allLede: 'Dalla più recente. I pulsanti qui sotto filtrano sul posto; senza JavaScript rimandano alle pagine delle faccette.',
    dimKind: 'Tipo',
    dimDomain: 'Ambito',
    dimStatus: 'Stato',
    dimTag: 'Tag',
    facetsAria: 'Navigazione a faccette',
    facetAll: 'Tutte →',
    clear: 'Azzera i filtri',
    noMatch: 'Nessuna nota soddisfa tutti i filtri selezionati.',
    allTags: 'Tutti i tag',
    chapters: (n) => (n === 1 ? '1 capitolo' : `${n} capitoli`),
  },
};
