/** 日本語 — Japanese. */
import type { UIStrings } from './types';

export const strings: UIStrings = {
  searchPlaceholder: 'この庭を検索…（Esc で閉じる）',
  searchHint: 'タイトル・見出し・本文を、この言語内で検索します。',
  searchEmpty: '一致するノートはありません。',
  searchUnavailable: '検索インデックスを読み込めませんでした。',
  searchUnit: '件',
  searchScopeAll: 'すべて',
  searchDialog: 'サイト内検索',
  searchInput: 'マニュアルを検索',
  searchResults: '検索結果',
  searchButton: '検索（⌘K）',

  languages: '言語',

  breadcrumb: 'パンくずリスト',
  contents: '目次',
  chapterNav: '章ナビゲーション',
  prev: '← 前へ',
  next: '次へ →',
  hub: 'ハブ',
  overview: '概要',
  updated: '更新',
  backlinks: 'バックリンク',
  localGraph: 'ローカルグラフ',
  lightbox: '画像ビューア',
  close: '閉じる',
  copied: 'コードをクリップボードにコピーしました',
  copyFailed: 'コピーに失敗しました（クリップボードを利用できません）',
  theme: 'ライト / ダークテーマの切り替え',
  github: 'GitHub のソースコード',
  menu: 'メニュー',
  skip: '本文へスキップ',
  partLabel: (roman) => `第${roman}部`,
  readingTime: (min) => `読了目安 ${min} 分`,
  footer: 'astro-inkstone デモ · ノートがそのままマニュアル、マニュアルがそのままデモ',

  landingTitle: '紙と墨の庭',
  landingDesc: "astro-inkstone — 書き込める Astro wiki。ドキュメント、wiki、デジタルガーデンのための紙とインクのタイポグラフィに、astro-inkbrush によるその場編集。このデモサイトはパッケージ自身で書かれたマニュアルです。",

  speakLabel: '平たく言えば →',
  diffLabel: '従来との違い →',

  kinds: {
    guide: { label: 'ガイド', desc: 'タスクに沿って進める手引き。まずここから読んで、組み込むところまで' },
    reference: { label: 'リファレンス', desc: 'ひとつのサブシステムの全体像を、つねに最新の状態で' },
    pattern: { label: 'パターン', desc: '名前を与える価値のある設計方針と、その理由' },
  },
  domains: {
    design: { label: 'デザイン', desc: 'トークン、テーマ、紙と墨の風合い' },
    pipeline: { label: 'パイプライン', desc: 'Markdown パイプライン — 方言、プラグイン、コンテンツガード' },
    components: { label: 'コンポーネント', desc: 'コンポーネント一式と、その組み合わせ方' },
    tooling: { label: 'ツーリング', desc: '各種チェックとレンダリング検査、そして CI' },
    editing: { label: '編集', desc: '編集の機構：ブロック、履歴、AI、受信箱' },
  },
  statuses: {
    seedling: { label: '芽生え', desc: '植えたばかりの下書き。まだ育っていない' },
    growing: { label: '成長中', desc: '書き進めている途中の、生きた文書' },
    evergreen: { label: '常緑', desc: '成熟し、手入れが続いている' },
  },

  browse: {
    kicker: '庭',
    kickerSub: 'ノートとして育つマニュアル',
    title: '紙と墨',
    titleSub: '育ちつづける作業ノートの庭',
    lede: (notes, domains) =>
      `astro-inkstone のマニュアルを、庭のように育てています。${notes} 件のノートが ${domains} 分野にわたり、種類・分野・タグから辿れます。このページにあるすべての描画効果は、このパッケージそのものの働きです。`,
    sep: '',
    stop: '。',
    source: 'ソース：',
    thisPackage: '本パッケージ',
    theEngine: 'CMS エンジン —',
    editsThesePages: 'がこのページそのものを編集する',
    recent: '最近の更新',
    recentSub: '直近に変わった 3 件',
    shelfCount: (n) => `主分野として ${n} 件 · すべて →`,
    allNotes: 'すべてのノート →',
    byKind: '種類別',
    byDomain: '分野別',
    byStatus: '成熟度別',
    byTag: 'タグ別',
    facetLede: (desc, n) => `${desc} — 全 ${n} 件。`,
    domainLede: (desc, n) => `${desc} — 主・副をあわせて ${n} 件。`,
    tagLede: (n) => `全 ${n} 件。`,
    tagDesc: (tag, n) => `タグ ${tag} のノート（${n} 件）`,
    facetDesc: (desc, n) => `${desc}（${n} 件）`,
    all: 'すべてのノート',
    allKicker: 'のこらずすべて',
    allEntries: (n) => `全 ${n} 件`,
    allDesc: (n) => `庭にあるすべてのノート（${n} 件）。新しい順、その場で絞り込みできます。`,
    allLede:
      '新しい順に並んでいます。下のボタンはその場で絞り込みます。JavaScript が無効なときは、それぞれの分類ページへ移動します。',
    dimKind: '種類',
    dimDomain: '分野',
    dimStatus: '状態',
    dimTag: 'タグ',
    facetsAria: '分類インデックス',
    facetAll: 'すべて →',
    clear: '絞り込みを解除',
    noMatch: '選んだ条件をすべて満たすノートはありません。',
    allTags: 'すべてのタグ',
    chapters: (n) => `全 ${n} 章`,
  },
};
