/** 한국어 — Korean. */
import type { UIStrings } from './types';

export const strings: UIStrings = {
  searchPlaceholder: '정원에서 검색… (Esc로 닫기)',
  searchHint: '제목, 섹션, 본문을 현재 언어에서 검색합니다.',
  searchEmpty: '일치하는 노트가 없습니다.',
  searchUnavailable: '검색 인덱스를 불러오지 못했습니다.',
  searchUnit: '건',
  searchScopeAll: '전체',
  searchDialog: '사이트 검색',
  searchInput: '매뉴얼 검색',
  searchResults: '검색 결과',
  searchButton: '검색 (⌘K)',

  languages: '언어',

  breadcrumb: '탐색 경로',
  contents: '목차',
  chapterNav: '장 탐색',
  prev: '← 이전',
  next: '다음 →',
  hub: '허브',
  overview: '개요',
  updated: '업데이트',
  backlinks: '연결된 언급',
  localGraph: '로컬 그래프',
  lightbox: '이미지 뷰어',
  close: '닫기',
  copied: '코드가 클립보드에 복사되었습니다',
  copyFailed: '복사하지 못했습니다 — 클립보드를 사용할 수 없습니다',
  theme: '라이트 / 다크 테마 전환',
  menu: '메뉴',
  skip: '본문 바로가기',
  partLabel: (roman) => `제${roman}부`,
  readingTime: (min) => `읽는 데 약 ${min}분`,
  footer: 'astro-inkstone 데모 · 노트가 곧 매뉴얼, 매뉴얼이 곧 데모',

  landingTitle: '종이와 먹의 정원',
  landingDesc: 'astro-inkstone 데모 사이트 — 노트 하나하나가 곧 이 패키지의 매뉴얼인, 분류로 가꾼 정원.',

  speakLabel: '쉽게 말하면 →',
  diffLabel: '기존 방식과의 차이 →',

  kinds: {
    guide: { label: '가이드', desc: '작업 흐름을 따라가는 안내: 여기서 시작해 바로 연결합니다' },
    reference: { label: '레퍼런스', desc: '한 서브시스템의 전체 그림, 항상 최신으로' },
    pattern: { label: '패턴', desc: '이름 붙일 만한 설계 관점과 그 이유' },
  },
  domains: {
    design: { label: '디자인', desc: '토큰, 테마, 종이와 먹의 질감' },
    pipeline: { label: '파이프라인', desc: 'Markdown 파이프라인 — 방언, 플러그인, 콘텐츠 가드' },
    components: { label: '컴포넌트', desc: '컴포넌트 모음과 조합하는 방법' },
    tooling: { label: '도구', desc: '각종 검사, 렌더링 점검, 그리고 CI' },
    editing: { label: '편집', desc: '편집 장치: 블록, 이력, AI, 수신함' },
  },
  statuses: {
    seedling: { label: '새싹', desc: '이제 막 심은 글감 — 아직 자라지 않았습니다' },
    growing: { label: '자라는 중', desc: '아직 써 나가는 중인, 살아 있는 문서' },
    evergreen: { label: '상록', desc: '무르익어 꾸준히 관리되는 글' },
  },

  browse: {
    kicker: '정원',
    kickerSub: '노트로 자라나는 매뉴얼',
    title: '종이와 먹',
    titleSub: '자라나는 작업 노트의 정원',
    lede: (notes, domains) =>
      `astro-inkstone 매뉴얼을 정원처럼 가꾸고 있습니다 — ${domains}개 분야에 걸친 노트 ${notes}편을 종류·분야·태그로 둘러볼 수 있습니다. 이 페이지의 렌더링 효과 하나하나가 곧 이 패키지가 일하는 모습입니다.`,
    sep: ' ',
    stop: '.',
    source: '소스:',
    thisPackage: '이 패키지',
    theEngine: 'CMS 엔진 —',
    editsThesePages: '명령이 바로 이 페이지들을 편집',
    recent: '최근 업데이트',
    recentSub: '가장 최근에 바뀐 세 편',
    shelfCount: (n) => `주 분야 ${n}편 · 전체 →`,
    allNotes: '모든 노트 →',
    byKind: '종류별',
    byDomain: '분야별',
    byStatus: '상태별',
    byTag: '태그별',
    facetLede: (desc, n) => `${desc} — 모두 ${n}편.`,
    domainLede: (desc, n) => `${desc} — 주·부 분야를 합쳐 ${n}편.`,
    tagLede: (n) => `모두 ${n}편.`,
    tagDesc: (tag, n) => `${tag} 태그가 달린 노트 (${n}편)`,
    facetDesc: (desc, n) => `${desc} (${n}편)`,
    all: '모든 노트',
    allKicker: '하나도 빠짐없이',
    allEntries: (n) => `모두 ${n}편`,
    allDesc: (n) => `정원의 모든 노트(${n}편)를 최신순으로, 즉석 필터와 함께.`,
    allLede: '최신순입니다. 아래 필터는 그 자리에서 바로 걸러 주고, JavaScript가 꺼져 있으면 해당 분류 페이지로 이동합니다.',
    dimKind: '종류',
    dimDomain: '분야',
    dimStatus: '상태',
    dimTag: '태그',
    facetsAria: '둘러보기 색인',
    facetAll: '전체 →',
    clear: '필터 지우기',
    noMatch: '선택한 조건을 모두 만족하는 노트가 없습니다.',
    allTags: '모든 태그',
    chapters: (n) => `총 ${n}장`,
  },
};
