/** Nederlands — Dutch. */
import type { UIStrings } from './types';

export const strings: UIStrings = {
  searchPlaceholder: 'Doorzoek de tuin… (Esc om te sluiten)',
  searchHint: 'Titels, secties en lopende tekst, in deze taal.',
  searchEmpty: 'Geen notitie komt overeen.',
  searchUnavailable: 'De zoekindex kon niet worden geladen.',
  searchUnit: 'pagina’s',
  searchScopeAll: 'Alles',
  searchDialog: 'Zoeken op de site',
  searchInput: 'Doorzoek de handleiding',
  searchResults: 'Zoekresultaten',
  searchButton: 'Zoeken (⌘K)',

  languages: 'Taal',

  breadcrumb: 'Kruimelpad',
  contents: 'Inhoud',
  chapterNav: 'Hoofdstuknavigatie',
  prev: '← vorige',
  next: 'volgende →',
  hub: 'Hub',
  overview: 'Overzicht',
  updated: 'bijgewerkt',
  backlinks: 'Gelinkte vermeldingen',
  localGraph: 'Lokale graaf',
  lightbox: 'Afbeeldingsweergave',
  close: 'Sluiten',
  copied: 'Code gekopieerd naar het klembord',
  copyFailed: 'Kopiëren mislukt – het klembord is niet beschikbaar',
  theme: 'Wissel tussen licht en donker thema',
  menu: 'Menu',
  skip: 'Direct naar de inhoud',
  partLabel: (roman) => `Deel ${roman}`,
  readingTime: (min) => `${min} min. leestijd`,
  footer: 'astro-inkstone-demo · de notities zijn de handleiding, de handleiding is de demo',

  landingTitle: 'Een tuin van papier en inkt',
  landingDesc: "astro-inkstone — de Astro-wiki waarin je schrijft. Papier-en-inkt-typografie voor documentatie, wiki's en digitale tuinen, met bewerken ter plekke via astro-inkbrush. Deze demo is de handleiding van het pakket, geschreven met het pakket zelf.",

  speakLabel: 'In gewone taal →',
  diffLabel: 'Vergeleken met eerder →',

  kinds: {
    guide: { label: 'Gids', desc: 'Stap voor stap langs een taak: begin hier en sluit alles aan' },
    reference: { label: 'Naslag', desc: 'Het volledige beeld van één subsysteem, actueel gehouden' },
    pattern: { label: 'Patroon', desc: 'Een ontwerpkeuze die een naam verdient, met de redenen erbij' },
  },
  domains: {
    design: { label: 'Ontwerp', desc: 'Tokens, theming, de look van papier en inkt' },
    pipeline: { label: 'Pipeline', desc: 'De Markdown-pipeline: dialect, plugins, de poortwachter voor de inhoud' },
    components: { label: 'Componenten', desc: 'De componentenset en hoe je die samenstelt' },
    tooling: { label: 'Tooling', desc: 'Controles, renderprobes en de CI-opzet' },
    editing: { label: 'Bewerken', desc: 'De bewerkingsmachine: blokken, geschiedenis, AI, postvak IN' },
  },
  statuses: {
    seedling: { label: 'Zaailing', desc: 'Een aanzet – geplant, nog niet volgroeid' },
    growing: { label: 'Groeiend', desc: 'Een levend document, nog volop in bewerking' },
    evergreen: { label: 'Groenblijvend', desc: 'Volgroeid en onderhouden' },
  },

  browse: {
    kicker: 'Tuin',
    kickerSub: 'de handleiding, gegroeid als notities',
    title: 'Papier & inkt',
    titleSub: 'een groeiende tuin van werknotities',
    lede: (notes, domains) =>
      `De handleiding van astro-inkstone, gegroeid als een tuin – ${notes === 1 ? '1 notitie' : `${notes} notities`} verdeeld over ${domains === 1 ? '1 domein' : `${domains} domeinen`}, te doorbladeren op soort, domein en tag. Elk rendereffect op deze pagina’s is het pakket zelf aan het werk.`,
    sep: ' ',
    stop: '.',
    source: 'Broncode:',
    thisPackage: 'dit pakket',
    theEngine: 'de CMS-engine –',
    editsThesePages: 'bewerkt precies deze pagina’s',
    recent: 'Onlangs bijgewerkt',
    recentSub: 'de laatste drie gewijzigde',
    shelfCount: (n) => `${n} primair · alles →`,
    allNotes: 'Alle notities →',
    byKind: 'Op soort',
    byDomain: 'Op domein',
    byStatus: 'Op status',
    byTag: 'Op tag',
    facetLede: (desc, n) => `${desc} – ${n === 1 ? '1 notitie' : `${n} notities`}.`,
    domainLede: (desc, n) => `${desc} – ${n === 1 ? '1 notitie' : `${n} notities`}, primair of secundair.`,
    tagLede: (n) => (n === 1 ? '1 notitie.' : `${n} notities.`),
    tagDesc: (tag, n) => `Notities met de tag ${tag} (${n})`,
    facetDesc: (desc, n) => `${desc} (${n === 1 ? '1 notitie' : `${n} notities`})`,
    all: 'Alle notities',
    allKicker: 'alles',
    allEntries: (n) => (n === 1 ? '1 item' : `${n} items`),
    allDesc: (n) => `Elke notitie in de tuin (${n}), nieuwste eerst, met directe filters.`,
    allLede: 'Nieuwste eerst. De knoppen hieronder filteren direct op de pagina; zonder JavaScript leiden ze naar de facetpagina’s.',
    dimKind: 'Soort',
    dimDomain: 'Domein',
    dimStatus: 'Status',
    dimTag: 'Tags',
    facetsAria: 'Facetnavigatie',
    facetAll: 'Alles →',
    clear: 'Filters wissen',
    noMatch: 'Geen notitie voldoet aan alle gekozen filters.',
    allTags: 'Alle tags',
    chapters: (n) => (n === 1 ? '1 hoofdstuk' : `${n} hoofdstukken`),
  },
};
