/** Türkçe — Turkish. */
import type { UIStrings } from './types';

export const strings: UIStrings = {
  searchPlaceholder: 'Bahçede ara… (kapatmak için Esc)',
  searchHint: 'Başlıklarda, bölümlerde ve metnin içinde, bu dilde arar.',
  searchEmpty: 'Eşleşen not yok.',
  searchUnavailable: 'Arama dizini yüklenemedi.',
  searchUnit: 'sayfa',
  searchScopeAll: 'Tümü',
  searchDialog: 'Site içi arama',
  searchInput: 'Kılavuzda ara',
  searchResults: 'Arama sonuçları',
  searchButton: 'Ara (⌘K)',

  languages: 'Dil',

  breadcrumb: 'Sayfa yolu',
  contents: 'İçindekiler',
  chapterNav: 'Bölümler arası gezinme',
  prev: '← önceki',
  next: 'sonraki →',
  hub: 'Genel bakış',
  overview: 'Genel bakış',
  updated: 'son güncelleme',
  backlinks: 'Geri bağlantılar',
  localGraph: 'Yerel grafik',
  lightbox: 'Görsel görüntüleyici',
  close: 'Kapat',
  copied: 'Kod panoya kopyalandı',
  copyFailed: 'Kopyalanamadı — panoya erişilemiyor',
  theme: 'Açık / koyu temayı değiştir',
  github: "GitHub'daki kaynak kodu",
  menu: 'Menü',
  skip: 'İçeriğe atla',
  partLabel: (roman) => `${roman}. Kısım`,
  readingTime: (min) => `${min} dk okuma`,
  footer: 'astro-inkstone demosu · notlar kılavuz, kılavuz da demo',

  landingTitle: 'Kâğıt ve mürekkepten bir bahçe',
  landingDesc: "astro-inkstone — içine yazabildiğiniz Astro wiki'si. Belgeler, wiki'ler ve dijital bahçeler için kâğıt-mürekkep tipografisi, astro-inkbrush ile yerinde düzenleme. Bu demo, paketin kendisiyle yazılmış kullanım kılavuzudur.",

  speakLabel: 'Sade dille →',
  diffLabel: 'Öncekilere göre →',

  kinds: {
    guide: { label: 'Rehber', desc: 'Görev odaklı adım adım anlatımlar: buradan başlayın, kurun' },
    reference: { label: 'Referans', desc: 'Bir alt sistemin tam resmi, güncel tutulur' },
    pattern: { label: 'Desen', desc: 'Ad koymaya değer bir tasarım tutumu, gerekçeleriyle' },
  },
  domains: {
    design: { label: 'Tasarım', desc: 'Token’lar, temalar, kâğıt-mürekkep görünümü' },
    pipeline: { label: 'İşlem hattı', desc: 'Markdown işlem hattı: lehçe, eklentiler, içerik bekçisi' },
    components: { label: 'Bileşenler', desc: 'Bileşen takımı ve birlikte nasıl kullanıldığı' },
    tooling: { label: 'Araçlar', desc: 'Denetimler, görüntüleme sınamaları ve CI düzeni' },
    editing: { label: 'Düzenleme', desc: 'Düzenleme makinesi: bloklar, geçmiş, yapay zekâ, gelen kutusu' },
  },
  statuses: {
    seedling: { label: 'Fide', desc: 'Bir taslak — dikildi, henüz büyümedi' },
    growing: { label: 'Büyüyor', desc: 'Yaşayan bir belge, hâlâ yazılıyor' },
    evergreen: { label: 'Her dem yeşil', desc: 'Olgun ve bakımlı' },
  },

  browse: {
    kicker: 'Bahçe',
    kickerSub: 'notlar hâlinde büyüyen kılavuz',
    title: 'Kâğıt ve mürekkep',
    titleSub: 'büyümeye devam eden bir çalışma notları bahçesi',
    lede: (notes, domains) =>
      `astro-inkstone kılavuzu, bir bahçe gibi büyütüldü — ${domains} alana yayılmış ${notes} not; türe, alana ve etikete göre gezinebilirsiniz. Bu sayfalardaki her dizgi ve görüntüleme efekti, iş başındaki paketin ta kendisi.`,
    sep: ' ',
    stop: '.',
    source: 'Kaynak kodu:',
    thisPackage: 'bu paket',
    theEngine: 'CMS motoru —',
    editsThesePages: 'tam da bu sayfaları düzenler',
    recent: 'Son güncellenenler',
    recentSub: 'en son değişen üç not',
    shelfCount: (n) => `${n} birincil · tümü →`,
    allNotes: 'Tüm notlar →',
    byKind: 'Türe göre',
    byDomain: 'Alana göre',
    byStatus: 'Duruma göre',
    byTag: 'Etikete göre',
    facetLede: (desc, n) => `${desc} — ${n} not.`,
    domainLede: (desc, n) => `${desc} — ${n} not (birincil ya da ikincil).`,
    tagLede: (n) => `${n} not.`,
    tagDesc: (tag, n) => `${tag} etiketli notlar (${n})`,
    facetDesc: (desc, n) => `${desc} (${n} not)`,
    all: 'Tüm notlar',
    allKicker: 'hepsi',
    allEntries: (n) => `${n} kayıt`,
    allDesc: (n) => `Bahçedeki tüm notlar (${n}), en yeniden eskiye, anında filtrelenebilir.`,
    allLede: 'En yeniler en üstte. Aşağıdaki filtreler sayfayı yerinde süzer; JavaScript yoksa ilgili dizin sayfalarına götürür.',
    dimKind: 'Tür',
    dimDomain: 'Alan',
    dimStatus: 'Durum',
    dimTag: 'Etiketler',
    facetsAria: 'Göz atma dizini',
    facetAll: 'Tümü →',
    clear: 'Filtreleri temizle',
    noMatch: 'Seçili filtrelerin tümüne uyan not yok.',
    allTags: 'Tüm etiketler',
    chapters: (n) => `${n} bölüm`,
  },
};
