/** Tiếng Việt — Vietnamese. */
import type { UIStrings } from './types';

export const strings: UIStrings = {
  searchPlaceholder: 'Tìm trong khu vườn… (Esc để đóng)',
  searchHint: 'Tìm theo tiêu đề, đề mục và nội dung, trong ngôn ngữ này.',
  searchEmpty: 'Không có ghi chú nào khớp.',
  searchUnavailable: 'Không tải được chỉ mục tìm kiếm.',
  searchUnit: 'trang',
  searchScopeAll: 'Tất cả',
  searchDialog: 'Tìm kiếm trên trang',
  searchInput: 'Tìm trong tài liệu',
  searchResults: 'Kết quả tìm kiếm',
  searchButton: 'Tìm kiếm (⌘K)',

  languages: 'Ngôn ngữ',

  breadcrumb: 'Đường dẫn điều hướng',
  contents: 'Mục lục',
  chapterNav: 'Điều hướng chương',
  prev: '← bài trước',
  next: 'bài sau →',
  hub: 'Tổng quan',
  overview: 'Tổng quan',
  updated: 'cập nhật',
  backlinks: 'Liên kết ngược',
  localGraph: 'Đồ thị cục bộ',
  lightbox: 'Trình xem ảnh',
  close: 'Đóng',
  copied: 'Đã sao chép mã vào bảng nhớ tạm',
  copyFailed: 'Sao chép thất bại — không truy cập được bảng nhớ tạm',
  theme: 'Chuyển giao diện sáng / tối',
  menu: 'Menu',
  skip: 'Chuyển đến nội dung chính',
  partLabel: (roman) => `Phần ${roman}`,
  readingTime: (min) => `Đọc khoảng ${min} phút`,
  footer: 'Bản demo astro-inkstone · ghi chú chính là tài liệu, tài liệu chính là bản demo',

  landingTitle: 'Khu vườn giấy và mực',
  landingDesc: "astro-inkstone — wiki Astro mà bạn viết ngay trên trang. Kiểu chữ giấy-và-mực cho tài liệu, wiki và vườn số, chỉnh sửa tại chỗ với astro-inkbrush. Bản demo này chính là sổ tay của gói, viết bằng chính gói đó.",

  speakLabel: 'Nói đơn giản là →',
  diffLabel: 'So với trước đây →',

  kinds: {
    guide: { label: 'Hướng dẫn', desc: 'Chỉ dẫn theo từng việc: bắt đầu ở đây, lắp vào dự án của bạn' },
    reference: { label: 'Tham khảo', desc: 'Bức tranh đầy đủ về một hệ thống con, luôn được cập nhật' },
    pattern: { label: 'Khuôn mẫu', desc: 'Một lối thiết kế đáng được đặt tên, cùng lý do đằng sau' },
  },
  domains: {
    design: { label: 'Thiết kế', desc: 'Token, chủ đề giao diện, chất giấy và mực' },
    pipeline: { label: 'Pipeline', desc: 'Pipeline Markdown: phương ngữ, plugin và lớp kiểm soát nội dung' },
    components: { label: 'Thành phần', desc: 'Bộ thành phần giao diện và cách phối hợp chúng' },
    tooling: { label: 'Công cụ', desc: 'Các phép kiểm tra, dò kết xuất và CI' },
    editing: { label: 'Biên tập', desc: 'Cỗ máy biên tập: khối, lịch sử, AI, hộp thư đến' },
  },
  statuses: {
    seedling: { label: 'Mầm', desc: 'Bản nháp vừa gieo, chưa kịp lớn' },
    growing: { label: 'Đang lớn', desc: 'Tài liệu sống, vẫn đang được viết tiếp' },
    evergreen: { label: 'Thường xanh', desc: 'Đã chín và được chăm sóc đều đặn' },
  },

  browse: {
    kicker: 'Khu vườn',
    kickerSub: 'tài liệu lớn lên thành từng ghi chú',
    title: 'Giấy và mực',
    titleSub: 'khu vườn ghi chú đang ngày một lớn',
    lede: (notes, domains) =>
      `Tài liệu hướng dẫn của astro-inkstone, được vun trồng như một khu vườn — ${notes} bài ghi chú thuộc ${domains} lĩnh vực, có thể duyệt theo thể loại, lĩnh vực và thẻ. Mọi hiệu ứng hiển thị trên những trang này đều là chính gói này đang làm việc.`,
    sep: ' ',
    stop: '.',
    source: 'Mã nguồn:',
    thisPackage: 'gói này',
    theEngine: 'engine CMS —',
    editsThesePages: 'chỉnh sửa chính những trang này',
    recent: 'Mới cập nhật',
    recentSub: 'ba bài thay đổi gần nhất',
    shelfCount: (n) => `${n} bài chính · tất cả →`,
    allNotes: 'Tất cả ghi chú →',
    byKind: 'Theo thể loại',
    byDomain: 'Theo lĩnh vực',
    byStatus: 'Theo trạng thái',
    byTag: 'Theo thẻ',
    facetLede: (desc, n) => `${desc} — ${n} bài.`,
    domainLede: (desc, n) => `${desc} — ${n} bài, tính cả lĩnh vực chính lẫn phụ.`,
    tagLede: (n) => `${n} bài.`,
    tagDesc: (tag, n) => `Ghi chú gắn thẻ ${tag} (${n} bài)`,
    facetDesc: (desc, n) => `${desc} (${n} bài)`,
    all: 'Tất cả ghi chú',
    allKicker: 'không sót bài nào',
    allEntries: (n) => `${n} mục`,
    allDesc: (n) => `Toàn bộ ghi chú trong vườn (${n} bài), mới nhất xếp trước, lọc ngay tại chỗ.`,
    allLede:
      'Mới nhất xếp trước. Các nút bên dưới lọc ngay tại trang; khi không có JavaScript, chúng dẫn sang trang phân loại tương ứng.',
    dimKind: 'Thể loại',
    dimDomain: 'Lĩnh vực',
    dimStatus: 'Trạng thái',
    dimTag: 'Thẻ',
    facetsAria: 'Chỉ mục duyệt',
    facetAll: 'Tất cả →',
    clear: 'Xóa bộ lọc',
    noMatch: 'Không có ghi chú nào khớp với tất cả bộ lọc đã chọn.',
    allTags: 'Tất cả thẻ',
    chapters: (n) => `${n} chương`,
  },
};
