/** 简体中文 — Simplified Chinese. */
import type { UIStrings } from './types';

export const strings: UIStrings = {
  searchPlaceholder: '搜索这座园地…（Esc 关闭）',
  searchHint: '搜标题、小节与正文，本语言内检索。',
  searchEmpty: '没有匹配的笔记。',
  searchUnavailable: '搜索索引加载失败。',
  searchUnit: '篇',
  searchScopeAll: '全部',
  searchDialog: '站内搜索',
  searchInput: '搜索这份手册',
  searchResults: '搜索结果',
  searchButton: '搜索（⌘K）',

  languages: '语言',

  breadcrumb: '面包屑',
  contents: '目录',
  chapterNav: '章节导航',
  prev: '← 上一章',
  next: '下一章 →',
  hub: '总览',
  overview: '总览',
  updated: '更新',
  backlinks: '反向链接',
  localGraph: '邻域 · local graph',
  lightbox: '图片查看器',
  close: '关闭',
  copied: '代码已复制到剪贴板',
  copyFailed: '复制失败，剪贴板不可用',
  theme: '切换浅色 / 深色主题',
  menu: '菜单',
  skip: '跳到正文',
  partLabel: (roman) => `第 ${roman} 部`,
  readingTime: (min) => `阅读约 ${min} 分钟`,
  footer: 'astro-inkstone 示范站 · 笔记即手册，手册即示范',

  landingTitle: '纸与墨的园地',
  landingDesc: "astro-inkstone——写得进去的 Astro 维基。为文档站、维基与数字花园准备的纸墨排版，搭配 astro-inkbrush 就地编辑。这个示范站就是这个包的使用手册，用它自己写成。",

  speakLabel: '说人话 →',
  diffLabel: '相比前作 →',

  kinds: {
    guide: { label: '指南', desc: '按任务走的教程：从这里开始，把它接起来' },
    reference: { label: '参考', desc: '一个子系统的完整说明，持续更新' },
    pattern: { label: '模式', desc: '一种值得命名的设计取向，以及背后的理由' },
  },
  domains: {
    design: { label: '设计', desc: 'token、主题、纸墨观感' },
    pipeline: { label: '管线', desc: 'Markdown 管线：方言、插件、内容守门' },
    components: { label: '组件', desc: '组件集，以及怎么搭配使用' },
    tooling: { label: '工具', desc: '检查、渲染体检与 CI' },
    editing: { label: '编辑机', desc: '编辑机：块编辑、修订历史、AI 与收件箱' },
  },
  statuses: {
    seedling: { label: '种子', desc: '刚种下的占位稿，还没长开' },
    growing: { label: '生长中', desc: '还在写的活文档' },
    evergreen: { label: '常青', desc: '成熟稳定，持续维护' },
  },

  browse: {
    kicker: '园地',
    kickerSub: '手册长成了笔记',
    title: '纸与墨',
    titleSub: '一座还在生长的工作笔记园地',
    lede: (notes, domains) =>
      `astro-inkstone 的使用手册，以园地的形式生长——${notes} 篇笔记、${domains} 个方向，可按形式、方向和标签浏览。这些页面上的每一处渲染效果，都是这个包在工作。`,
    sep: '',
    stop: '。',
    source: '源码：',
    thisPackage: '本包',
    theEngine: 'CMS 引擎——',
    editsThesePages: '编辑的就是这些页面',
    recent: '最近更新',
    recentSub: '最近改动的三篇',
    shelfCount: (n) => `${n} 篇以此为主 · 全部 →`,
    allNotes: '全部笔记 →',
    byKind: '按形式',
    byDomain: '按方向',
    byStatus: '按成熟度',
    byTag: '按标签',
    facetLede: (desc, n) => `${desc}——共 ${n} 篇。`,
    domainLede: (desc, n) => `${desc}——共 ${n} 篇，主方向或次方向。`,
    tagLede: (n) => `共 ${n} 篇。`,
    tagDesc: (tag, n) => `带 ${tag} 标签的笔记（${n} 篇）`,
    facetDesc: (desc, n) => `${desc}（${n} 篇）`,
    all: '全部笔记',
    allKicker: '一篇不落',
    allEntries: (n) => `共 ${n} 篇`,
    allDesc: (n) => `园地里的全部笔记（${n} 篇），最新的在前，可即时筛选。`,
    allLede: '最新的在前。下面的筛选项就地过滤；没有 JavaScript 时它们会跳到对应的分类页。',
    dimKind: '形式',
    dimDomain: '方向',
    dimStatus: '状态',
    dimTag: '标签',
    facetsAria: '浏览索引',
    facetAll: '全部 →',
    clear: '清除筛选',
    noMatch: '没有笔记同时满足所选条件。',
    allTags: '全部标签',
    chapters: (n) => `${n} 章`,
  },
};
